name: CI setup
description: Checkout repo + setup Dagger

inputs:
  fetch-depth:
    description: ""
    required: false
    default: "1"
  fetch-tags:
    description: ""
    required: false
    default: "false"
  dagger-version:
    description: ""
    required: false
    default: "latest"

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v6
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        fetch-tags: ${{ inputs.fetch-tags }}

    - name: Setup dagger
      uses: dagger/dagger-for-github@v8.2.0
      with:
        version: ${{ inputs.dagger-version }}
