name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.0'

      - name: Build
        run: go build -o bin/url-shortener-web ./cmd/web

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: url-shortener-web
          path: bin/url-shortener-web
          compression-level: 6
